export const galleryEvents: { id: string; src: string; alt: string; width: number; height: number }[] = [
  { id: "imgE6", src: "/gallery/events/bearFamilycasa5k.jpg", alt: "Group of runners and family before race start", width: 800, height: 600 },
  { id: "imgE7", src: "/gallery/events/johnyBearcasa5k.jpg", alt: "Runner celebrating at finish line", width: 800, height: 600 },
  { id: "imgE8", src: "/gallery/events/runningBearcasa5k.jpg", alt: "Runners on the course during a sunny day", width: 800, height: 600 },
  { id: "imgE9", src: "/gallery/events/runningBearfourcasa5k.jpg", alt: "Close-up of a runner mid-stride", width: 800, height: 600 },
  { id: "imgE10", src: "/gallery/events/runningBearthreecasa5k.jpg", alt: "Group of runners passing a checkpoint", width: 800, height: 600 },
  { id: "imgE11", src: "/gallery/events/runningBeartwocasa5k.jpg", alt: "Volunteer handing water to runners", width: 800, height: 600 },
  { id: "imgE1", src: "/gallery/events/477042486_659149196830259_7450223642701792381_n.jpg", alt: "Runners posing for a group photo", width: 800, height: 600 },
  { id: "imgE2", src: "/gallery/events/carlsoRunning_1.1.1.jpg", alt: "Runner crossing a scenic trail", width: 800, height: 600 },
  { id: "imgE3", src: "/gallery/events/johnyfifeksighn.jpg", alt: "Runner tying shoes before race", width: 800, height: 600 },
  { id: "imgE4", src: "/gallery/events/juanjuanbeforerun.jpg", alt: "Two runners stretching before the start", width: 800, height: 600 },
  { id: "imgE5", src: "/gallery/events/juanjuanrun.jpg", alt: "Runner sprinting toward the finish", width: 800, height: 600 },
  { id: "imgE13", src: "/blogPhotos/dia_de_lost_muerto_picking_up_bid.jpg", alt: "dia de lost muertos event picking up bibs", width: 800, height: 600 },
  { id: "imgE14", src: "/blogPhotos/dia_de_lost_muerto_runners_group.jpg", alt: "dia de lost muertos event runners group", width: 800, height: 600 },
  { id: "imgE15", src: "/blogPhotos/laredo_marathon_johny_friend.jpg", alt: "laredo half marathon before group", width: 800, height: 600 },
  { id: "imgE16", src: "/blogPhotos/laredo_marathon_johny_mom_bear.jpg", alt: "laredo half marathon starting line", width: 800, height: 600 },
  { id: "imgE17", src: "/blogPhotos/laredo_marathon_johny_mom.jpg", alt: "laredo half marathon running event", width: 800, height: 600 },
  { id: "imgE18", src: "/blogPhotos/austinMarathon26/austinMarathon_johny_running.jpg", alt: "Johny running during the Austin Marathon", width: 800, height: 600 },
  { id: "imgE19", src: "/blogPhotos/austinMarathon26/austinMarathon_running_crowd.JPG", alt: "Running crowd at Austin Marathon", width: 800, height: 600 },
  { id: "imgE20", src: "/blogPhotos/austinMarathon26/austinMarathon_capitol_and_johny.JPG", alt: "Capitol and Johny at Austin Marathon finish line", width: 800, height: 600 },
  { id: "imgE21", src: "/blogPhotos/austinMarathon26/austinMarathon_team_photo_with_medals.jpg", alt: "Team photo with medals at Austin Marathon", width: 800, height: 600 },
  { id: "imgE22", src: "/blogPhotos/austinMarathon26/austinMarathon_medals_with_bbq.JPG", alt: "Austin Marathon medals with BBQ celebration", width: 800, height: 600 },
];
export default galleryEvents;